<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SimpleTunnelSSH.Core\SimpleTunnelSSH.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SimpleTunnelSSH</AssemblyName>
    <Product>Simple Tunnel SSH</Product>
    <Version>0.0.2</Version>
    <ApplicationIcon>Assets\App.ico</ApplicationIcon>
  </PropertyGroup>

</Project>